name: toolventory_mate
description: "Tool inventory app by Martin Caputti"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.4.5
  firebase_database: ^11.1.6
  flutter_svg: ^2.0.14
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^3.6.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff" # Fondo de la splash screen
  image: assets/images/toolventorylogo.png # Ruta de la imagen del logo
  android: true
  ios: true
  web: true
